### ISSUE TITLE
0.8.x and 0.9.x Compatibility?

### ISSUE THREAD

**Issue by mikelococo** [datdamnzotz/FoundryVTT-DnD-Audio-Bundle-Hammer-Home#1]
The compatibleCoreVersion in https://github.com/datdamnzotz/FoundryVTT-DnD-Audio-Bundle-Hammer-Home/blob/master/module.json#L7 is still set to 0.8.0, which:

- Is a pre-release version of the 0.8.x series, not a stable release
- Is not the most recent in the 0.8.x stable series
- Is about to become a major release behind, as 0.9.x has had its third testing release

This is mostly a content module, and although it has a db file in it I'm not aware of any compatibility problems with more recent releases. Is there any chance of updating compatibleCoreVersion to accurately convey the module's compatibility so people know if they can safely install it on modern Foundry releases?

**Comment by datdamnzotz** [comment]
Same issue as the other bundles, I'll upgrade them all at once once I get time.  I'll track it in:
https://github.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-1/issues/5
