### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tukkek** [datdamnzotz/FoundryVTT-DnD-Audio-Bundle-Hammer-Home#3]
Hi, this project is missing licensing information. I imagine it is the same as for the other listed projects? As in: https://github.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-1/blob/master/Licensing.pdf

Either way, I'd suggest adding explicit information in this regard - as public Git-Hub projects are open-source by necessity, might as well make sure potential users understand how they can or can't use these files.

If you haven't made up your mind on a particular license yet, I'd suggest CC0 as I see very many media bundles distributed under it.https://creativecommons.org/publicdomain/zero/1.0/deed

**Comment by datdamnzotz** [comment]
Thanks for the suggestion. It was under the /src/ directory.  I moved it to the root to be more visible.

**Comment by tukkek** [comment]
Thank you!
